# Generated by Django 2.2.13 on 2020-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
