# Generated by Django 2.2.13 on 2020-06-13 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
