# Generated by Django 2.2.13 on 2020-06-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todoitem_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='created',
            new_name='created_at',
        ),
    ]
